docs/UserGuide.md
=> Update delete command in User Guide

docs/UserGuide.md
=> Update list command in UG

README.md, docs/AboutUs.md, docs/DeveloperGuide.md
=> Modify README.md and DeveloperGuide.md with simple use cases

docs/DeveloperGuide.md
- Made changes to the priority of user story for `help` command
- Changed the sentencing in the use case for `help` command
=> Update Developer Guide for help command

src/main/java/seedu/address/logic/commands/ListCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java
Added a response when there are no candidates in the system.
Closes #40
=> Add list command

src/main/java/seedu/address/commons/util/HelpWindowUtil.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/java/seedu/address/commons/util/HelpWindowUtilTest.java
Things that have been added in this commit
* Link to user guide from Help Window will open web browser
* Create new tests for HelpWindowUtil
=> Create HelpWindowUtil class

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Course.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/StudentId.java, src/main/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicate.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/predicate/CourseContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicateTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Issue #79: Change `studentID` to `studentId` and its related classes

docs/AboutUs.md, docs/UserGuide.md
- Updated `add` command in UG
- Re-ordered teammates in alphabetical order in `AboutUs`
Closes #58.
=> Issue #58: Update `add` command in UG/DG

docs/DeveloperGuide.md, docs/UserGuide.md
Update the Developer Guide and User Guide based on my current implementation of the `schedule` command. 
As noted in the UG, the `schedule` command is still a WIP, so changes to the UG or DG may occur in subsequent updates.
Closes #66 
Closes #67
=> Update DG and UG with schedule command

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Availability.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/person/AvailabilityTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Added a new prefix avail/ to capture the available dates of each candidate.
- Dates are currently as: 1 (Monday) to 7 (Sunday).
- Have yet to update DG and UG
Closes #71
=> Add availabilities for each candidate

docs/AboutUs.md, docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java
Currently the HelpWindow shows the commands from previous version. 
Let's update the content of the HelpWindow with the new commands for this version.
* sort
* edit 
* delete 
Let's update the UserGuide for this new commands as well. 
closes #92
=> Update content of HelpWindow

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/candidate/ApplicationStatus.java, src/main/java/seedu/address/model/candidate/Candidate.java, src/main/java/seedu/address/model/candidate/Course.java, src/main/java/seedu/address/model/candidate/InterviewStatus.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/model/candidate/CandidateTest.java, src/test/java/seedu/address/model/candidate/CourseTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Refactored check for duplicate records to use only `studentId`
- Added deeper validation for `course` input
- Refactored `ApplicationStatus` and `InterviewStatus` attribute and constructor
- Fixed test cases
- Added minor refactors to feedback displayed to user
Closes #80.
=> Issue #80: Enhancing `add` command

build.gradle
=> Issue #103: Enable assertions in gradle

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ScheduleCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java
=> Integrate InterviewSchedule with clear command

src/main/java/seedu/address/MainApp.java
=> Update MainApp.java for trial release

src/main/java/seedu/address/ui/FocusCard.java, src/main/java/seedu/address/ui/FocusListPanel.java, src/main/java/seedu/address/ui/InterviewCard.java, src/main/java/seedu/address/ui/InterviewListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/CandidateListCard.fxml, src/main/resources/view/FocusListCard.fxml, src/main/resources/view/FocusListPanel.fxml, src/main/resources/view/InterviewListCard.fxml, src/main/resources/view/InterviewListPanel.fxml, src/main/resources/view/MainWindow.fxml
This PR includes the creation of three adjustable bottom panels in the GUI layout.
Left panel: full list of candidates
Middle panel: (WIP) placeholder for single candidate view
Right panel: (WIP) placeholder for confirmed interviews
Closes #125
=> Issue #125: Create placeholders for GUI bottom panels

docs/UserGuide.md
- Update add command usage
- Remove tags related notes
Closes #95.
=> Issue #95: Update `add` command in User Guide

src/main/java/seedu/address/model/candidate/Availability.java, src/main/java/seedu/address/ui/CandidateCard.java, src/main/resources/view/DarkTheme.css, src/test/java/seedu/address/model/candidate/AvailabilityTest.java
=> Improve availability UI

docs/UserGuide.md, src/main/java/seedu/address/commons/core/LogsCenter.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json, src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
- Updated files related with `addressbook.json` data file to `talentassistant.json` incl. preferences and log files
**NOTE to Reviewers**: don't mind just verify the spelling closely. Thanks! 🍻 
Closes #174.
=> Issue #174: Refactor data filename to `talentassistant` instead of `addressbook`

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java, src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java, src/main/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/interview/predicate/SameInterviewPredicate.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteScheduleCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
=> Issue #160 Implement `schedule delete` command

src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java, src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java, src/main/java/seedu/address/logic/parser/schedule/AddScheduleCommandParser.java, src/main/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParser.java, src/main/java/seedu/address/logic/parser/schedule/EditScheduleCommandParser.java, src/main/java/seedu/address/model/InterviewSchedule.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/interview/Interview.java, src/main/java/seedu/address/model/interview/UniqueInterviewList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java, src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java, src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java, src/test/java/seedu/address/model/interview/UniqueInterviewListTest.java, src/test/java/seedu/address/testutil/TypicalInterviews.java
Hey y'all! After contemplating if I should go with `schedule edit INDEX DATE_TIME` or  `schedule edit INDEX at/DATE_TIME`, I decided to go with the one with the prefix because the original one is prone to bugs such as `IndexOutOfBoundsException` or the code will look hard-coded/amateurish. If y'all want to stick to the old one lmk, I can change it back!
Closes #159
=> Issue #159: Implement `schedule edit` command

docs/DeveloperGuide.md, docs/UserGuide.md
=> Issue #111: Add `edit` command related documentation

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/candidate/Email.java, src/main/java/seedu/address/model/candidate/Seniority.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/candidate/EmailTest.java, src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/CourseContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/EmailContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/PhoneContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/StudentIdContainsKeywordsPredicateTest.java, src/test/java/seedu/address/testutil/CandidateBuilder.java, src/test/java/seedu/address/testutil/CandidateUtil.java
=> Issue #207: Add `email` back into `add` command

src/main/resources/view/DarkTheme.css, src/main/resources/view/FocusListCard.fxml
=> Update `FocusCard` UI

src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
=> Update `HelpWindow` UI

src/main/java/seedu/address/ui/FocusCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/FocusListCard.fxml
=> Update profile picture in focus card

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
Hey guys @tiewweijian @domlimm @charmainehly @LeeEnEn I also tried to organise the commands into different sections in the UG and added a link to each section in the `Features` section . Can always rename/reorganise them as you wish. This is just a rough/draft template for now.
I think you can view the UG on my branch to see the visual changes! 
Edit: https://github.com/lzan98/tp/blob/185186-schedule-ug/docs/UserGuide.md
Closes #185 
Closes #186
=> Update `schedule` commands in UG

src/main/java/seedu/address/ui/FocusCard.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/FocusListCard.fxml, src/test/java/seedu/address/ui/FocusCardTest.java
Focus card when there is no interview for the candidate:
When there is an interview:
Closes #195
=> Add schedule details in focus card

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/candidate/Candidate.java, src/main/java/seedu/address/model/candidate/Email.java, src/main/java/seedu/address/model/candidate/StudentId.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/FocusCard.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/FocusListCard.fxml, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml, src/test/data/JsonAddressBookStorageTest/invalidAndValidCandidateAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidCandidateAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateCandidateAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidCandidateAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalCandidatesAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/candidate/CandidateTest.java, src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/CourseContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/EmailContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/PhoneContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/candidate/predicate/StudentIdContainsKeywordsPredicateTest.java, src/test/java/seedu/address/testutil/CandidateBuilder.java, src/test/java/seedu/address/testutil/TypicalCandidates.java
- Update format of `studentId` from `EXXXXXXX` to `AXXXXXXXX`
- Update test cases on this change
Closes #192 and #196.
@charmainehly @LeeEnEn @lzan98 @tiewweijian hey guys, do take note.
After this PR and PR #209 that address Issue #207, we now have to take in `email` when adding Candidate. (You can just hover to see the overview of the tagged PR/Issue, thanks!)
=> Issue #192: Refactor `candidate` model

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/testutil/TypicalInterviews.java
Hey @lzan98 hope you didn't mind ! I had quite a bit of time on my hand and helped you complete #154. Let me know if there are other things to change too!! 
closes #154
=> Change interviewList to interviewSchedule

src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
- Update user guide link to link to command summary
- Refactor position for button in window
- Update help window header
Closes #237.
=> Issue #237: Refactor `HelpWindow`

src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java, src/main/java/seedu/address/model/interview/Interview.java, src/test/java/seedu/address/testutil/TypicalInterviews.java
Apparently, the issue currently extends to schedule add command as well. 😅Good spot @LeeEnEn!
=> Fix office hours logic 

src/main/java/seedu/address/ui/FocusCard.java, src/main/java/seedu/address/ui/Styles.java
=> Remove random color generator for profile picture

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/ui/MainWindow.java
=> 249-Fix `Delete` Bug

src/main/java/seedu/address/logic/commands/RemarkCommand.java
=> Issues #254: Add loop to RemarkCommand to sync remark update to interview schedule

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/storage/JsonSerializableInterviewSchedule.java
Just a quick and small change to MainApp when either JSON files are missing, and to model the behaviour when duplicate/conflicting interviews are found to that of AB3.
We have to make it explicitly clear in UG what not to do when editing the files too.
Closes #232
=> Update logic of loading JSON files

src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java, src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java, src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/InterviewSchedule.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/candidate/Candidate.java, src/main/java/seedu/address/model/candidate/UniqueCandidateList.java, src/main/java/seedu/address/model/interview/Interview.java, src/main/java/seedu/address/model/interview/UniqueInterviewList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/ClearScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java, src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
=> Issue #248 Implement `schedule clear` command

src/main/java/seedu/address/logic/commands/RemarkCommand.java, src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java, src/main/java/seedu/address/ui/FocusCard.java, src/main/java/seedu/address/ui/MainWindow.java
Now `FocusCard` will show the message after `RemarkCommand` is used. 
closes #253
=> #253-Refresh `FocusCard` when using `RemarkCommand`

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/candidate/Candidate.java, src/main/java/seedu/address/model/candidate/UniqueCandidateList.java, src/main/java/seedu/address/model/interview/Interview.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/RemarkCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/candidate/UniqueCandidateListTest.java
- Enforcing constraints on edit fields
- Add `phoneNumber` to be unique for each `Candidate`
- Minor refactor: Remove `tags` (Please view from [https://github.com/AY2122S2-CS2103-F11-2/tp/compare/master...domlimm:102-edit-command-rework?expand=1#diff-3f3fedfeaaba3e25ad4ec2fc88e5ba721e42776519d18345851bfa5a8d10ec88](here))
Leon did up the updating of the Interview schedule upon executing the `EditCommand` in PR #228.
Converting it to draft PR first to settle Issue #102 ([Point 3](https://github.com/AY2122S2-CS2103-F11-2/tp/issues/102#issuecomment-1080275444)).
Thank you for all the help! @charmainehly @LeeEnEn @lzan98 @tiewweijian ❤️ I appreciate it from the bottom of my heart. Much love x
Closes #102. Wraps up all the discussion in there.
=> Issue #102: Edit command rework

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Change add command feedback

src/main/java/seedu/address/logic/commands/FocusCommand.java
=> Change feedback for `FocusCommand`

docs/UserGuide.md
=> Update UG with schedule clear and warning for JSON

src/main/java/seedu/address/ui/FocusCard.java
=> Fix profile picture not showing

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java, src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java, src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java, src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java, src/test/java/seedu/address/testutil/TypicalInterviews.java
Closes #271 and update the priority of checks when adding/editing interview.
=> Fix feedback messages and update logic for scheduling

src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java, src/main/java/seedu/address/ui/MainWindow.java
Hey guys I changed the feedback panel so it reflects the correct command feedback. 
I think there might still be an error with some exception catching ! WIll test it out a bit more first, then get back to you guys again! 🥂 
Thanks guys :')))
=> Feedback panel will reflect correct message

src/main/java/seedu/address/ui/MainWindow.java
Closes #285.
Solves https://github.com/AY2122S2-CS2103-F11-2/tp/issues/240#issuecomment-1084552213.
=> Issue #285: Bugfix: command textfield does not clear when focus panel is not loaded

src/main/java/seedu/address/ui/FocusCard.java
=> Update profile picture to show for `name` containing numbers

src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java, src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java, src/main/java/seedu/address/model/interview/Interview.java, src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java, src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
=> Change date format to dd-MM-YYYY

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/RemarkCommand.java
=> Fix new line in feedback box messages

docs/UserGuide.md
=> Fix Tables UG

src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
=> Add Strict ResolverStyle to DateTimeFormatter

docs/UserGuide.md
Closes #317 
Closes #321 
Closes #326 
Closes #333 
Closes #336
=> Update UG for PED bugs and suggestions

docs/team/charmainehly.md
To be updated further!!
Closes #352
=> Issue #352: Update skeletal PPP with summary of contributions

docs/DeveloperGuide.md
=> Issue #364: Add acknowledgement for application's icon into DG

src/main/java/seedu/address/model/InterviewSchedule.java
=> Change time to be 30 minutes instead of 31 minutes

docs/UserGuide.md
=> Update edit command format in UG

src/main/java/seedu/address/model/candidate/Seniority.java, src/main/java/seedu/address/storage/JsonAdaptedInterview.java, src/test/java/seedu/address/model/candidate/SeniorityTest.java, src/test/java/seedu/address/storage/JsonAdaptedInterviewTest.java
=> Create test cases for JsonAdaptedInterview

src/main/java/seedu/address/logic/commands/EditCommand.java
@charmainehly @LeeEnEn @lzan98 @tiewweijian Guys, to note that Issue #349 has been given the go to fix by prof.
Closes #349.
=> Issue #349: Fix bug in ellipsis for edit command message usage

docs/DeveloperGuide.md, docs/team/charmainehly.md
Details of PR: Adds manual test cases, use cases and user stories to the developer guide for the `remark`, `view`, `sort` and `find` command. (pending implementation details)
Note: this commit also updates details for the PPP
Closes #388 
Closes #389
=> Issue #388/389: Update developer guide and PPP

docs/DeveloperGuide.md
=> Issue #418: Add `add` command manual testing

docs/DeveloperGuide.md
=> Issue #424: Bug Fix: Add line breaks for add candidate manual testing

docs/DeveloperGuide.md
=> Update edit details in UG

docs/team/lzan98.md
=> Finalise PPP

docs/team/domlimm.md
=> Issue #411: Finalise PPP

docs/team/leeenen.md
=> Finalize PPP

docs/DeveloperGuide.md
=> Update saving data details in UG

docs/team/lzan98.md
Hopefully this change removes the extra line in my PPP.
=> Final change to PPP

docs/DeveloperGuide.md
=> Remove additional line in DG

docs/DeveloperGuide.md, docs/UserGuide.md
=> Fix remove link

src/main/java/seedu/address/logic/commands/RemarkCommand.java
=> Issue #450: Fix bug in remark message
