- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/model/Model.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
Modified the system to display the message `There are no candidates in the system!` instead of the current `The provided candidate index is invalid` when attempting to `delete` a candidate from an empty list.
@LeeEnEn Since you previously used the message in the `ListCommand`, I shifted the message out to the main `commons.core.Messages` for easier import and access. Hence, I assigned you to review as well to double confirm the changes (I have run the `ListCommandTest` to ensure it passes, but just double-check in case.) 😄
#43
> Add delete command and empty list message

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/ApplicationStatus.java
- src/main/java/seedu/address/model/person/InterviewStatus.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/person/ApplicationStatusTest.java
- src/test/java/seedu/address/model/person/InterviewStatusTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Currently the candidates do not have statuses tagged to them. 
Let's add new attributes into the Candidate  
- ApplicationStatus
- InterviewStatus
Currently no new changes in the workflow (i.e. adding a new user will not require new commands), default values for new Candidates will be `pending` for both `ApplicationStatus` and `InterviewStatus`. The UI to display the statuses of the candidate as well.
> Add ApplicationStatus and InterviewStatus

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/candidate/ApplicationStatusTest.java
- src/test/java/seedu/address/model/candidate/InterviewStatusTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Currently `ApplicationStatus` and `InterviewStatus` are changed manually. 
Let's change it so that `ApplicationStatus` when changed to `Accepted` or `Rejected`, it will trigger `InterviewStatus` to be `Completed`. 
closes #108
> Create trigger for `ApplicationStatus`

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/InterviewSchedule.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/interview/predicate/AllWithinTimePeriodPredicate.java
- src/main/java/seedu/address/model/interview/predicate/ThisMonthWithinTimePeriodPredicate.java
- src/main/java/seedu/address/model/interview/predicate/ThisWeekWithinTimePeriodPredicate.java
- src/main/java/seedu/address/model/interview/predicate/TodayWithinTimePeriodPredicate.java
- src/main/java/seedu/address/model/interview/predicate/WithinTimePeriodPredicate.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/InterviewScheduleTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/interview/predicate/AllWithinTimePeriodPredicateTest.java
- src/test/java/seedu/address/model/interview/predicate/ThisMonthWithinTimePeriodPredicateTest.java
- src/test/java/seedu/address/model/interview/predicate/ThisWeekWithinTimePeriodPredicateTest.java
- src/test/java/seedu/address/model/interview/predicate/TodayWithinTimePeriodPredicateTest.java
Currently, the view command only allows the user to view all scheduled interviews.
The user is not able to filter the interview schedule by time period.
Let's enhance the `view` command with three time period keywords: 'today', 'week' and 'month', to display scheduled interviews within the time period from when the command is entered. Let's also modify the implementation of InterviewSchedule related methods in the ModelManager so that the interviews will be sorted from the earliest to latest interview slot in the UI panel.
Logic:
* `today` = must be after the current date time, and within the same day
* `week` = must be after the current date time, and within 7 days of current date time
* `month` = must be after the current date time, and within 1 month of current date time
* `all` (or if …
> Issue #124: Enhance `view` command to view interviews `today`, this `week` or this `month`

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
- src/main/java/seedu/address/storage/JsonAdaptedCandidate.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
- src/test/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicateTest.java
Currently, the sort and find command are only able to function with previous candidate fields.
The user is therefore not able to search across seniority, interview status and application status.
In this PR: Let's add the switch-case statements for the fields above, and also the relevant ContainsKeywordsPredicate classes for the find command.
Note: This commit also fixes the implementation for updateSortedCandidateList() in the ModelManager. Error in the previous implementation results in the original addressbook candidate list being modified.
Closes #89 and Closes #153
> Issue #89/#153: Update find/sort command for Seniority, Application Status and Interview Status

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/model/InterviewSchedule.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/model/InterviewScheduleTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Brief summary of what this feature does:
- Deletes interviews on startup of the application only
- Deletes interviews that are 31 mins ago, since each interview time slot is 30 minutes long
Closes #140
> Update automatic deletion of past scheduled interviews

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/model/candidate/predicate/AvailabilityContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/model/candidate/predicate/AvailabilityContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java
- Added additional field `availability` for user to search for when using the `find` command
- Added supporting test cases
- Fix minor bugs
Thanks @charmainehly for creating the issue!
Closes #162.
> Issue #162: `find` based on Candidate's availability

- src/main/java/seedu/address/logic/commands/FocusCommand.java
- src/main/java/seedu/address/ui/CandidateCard.java
- src/main/java/seedu/address/ui/FocusCard.java
- src/main/java/seedu/address/ui/Styles.java
- src/main/resources/view/CandidateListCard.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/FocusListCard.fxml
- Shift constants style related codes to a separate file to import from
- Update UI of `availability` tags
- Add a new `primary` colour of `blue` for `Scheduled` of `interviewStatus`
- Fix command message for `focus` command
- Fix missing `COM` tag for `seniority` in `FocusCard`
<hr>
<h4>Current UI</h4>
<p><b>Note: Window resized manually. Will have to change to new dimensions preset preferences</b></p>
<hr>
Closes #178.
> Issue #178: Polishing the `UI`

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/commons/core/GuiSettings.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/FocusListCard.fxml
- src/main/resources/view/InterviewListCard.fxml
- src/main/resources/view/MainWindow.fxml
Currently, minimising the screen will cause some text misalignment and truncation of information.
This might affect the user's ease of viewing.
Let's include the following changes:
* a scroll pane in the middle panel to allow overflow scrolling
* headers for each panel to indicate each panel's use
* larger default window size for the gui app
* extend the feedback box to have a larger minimum height
<br> **Previous UI upon minimisation:**
<br> **Updated UI upon minimisation:**
_Note to reviewers: appreciate your help to double check the default viewing dimensions! :) Feel free to leave comments on removing/modifying any of the above changes, or modifying them at your end after the merge!_
Closes #190
> Issue #190: Fix split pane overflow scroll and headers

- src/main/java/seedu/address/model/candidate/Seniority.java
- src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
- src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java
Currently, the find command searches for all fields under each candidate via the candidate.toString() method.
This causes the search to include irrelevant strings e.g."availability" and "phone". This also results in edge cases
where find k/availability f/candidate will bring up positive search results.
Let's fix the implementation in the CandidateContainsKeywordsPredicate class so that the find command will separately check through each of the candidate's fields and return through if any of these fields include any of the keywords.
Note: Small edit to Seniority class and predicate class to enable the find command to search according to the text that
the candidate card in the gui displays, i.e. COM1, COM2 etc.
Closes #189
> Fix implementation of find command for candidate field

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
Currently `InterviewStatus` will be triggered to `Completed` once `ApplicationStatus` is set to `Accepted` or `Rejected`. 
Let's decouple the two status to make them independent. 
Closes #203
> #203-Remove `InterviewStatus` Trigger

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/ui/CandidateCard.java
- src/main/java/seedu/address/ui/FocusCard.java
- src/main/resources/view/CandidateListCard.fxml
- src/main/resources/view/FocusListCard.fxml
- src/main/resources/view/MainWindow.fxml
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
This PR includes:
1. edits to the UI to make it smoother, fixes the expansion in the middle panel
2. added back `course` and `seniority` to candidate cards after some discussion w dom - TDLR: felt that as a user, might want to be able to view the course and seniority of candidates easily on the left panel to preliminarily decide the priority of scheduling interviews for these candidates.
3. standardises the prefixes used for `sort` and `find` command - TLDR: was on the fence between using the prefixes for the `add` command as the `ATTRIBUTE_FIELD` values for the `sort` and `find` commands. But after consideration, decided to instead shorten `applicationstatus` to `appstatus` and `interviewstatus` to `intstatus`, while leaving the rest of the fields typed out in full. This is to make it …
> Issue #240: Address issues relating to `sort`, `find`, `remark` and UI

- docs/UserGuide.md
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/RemarkCommand.java
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/ui/FocusCard.java
- src/main/resources/view/ResultDisplay.fxml
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Includes 
1. temporary fix to profile photo colour as the bug disallows me from loading up any profiles ( @LeeEnEn see issue tagged in the bug thread)
2. slight updates to documentation of UG
3. allow wrapping of result display box
@lzan98 appreciate your help to confirm that the deletion of the lines from `RemarkCommand` and `EditCommand` doesnt affect any behaviour from testings that you have done? - as from my understanding the setCandidate() method should not update the indexes of the candidates etc.
Closes #264
> Issues #263: Fix refresh on `view` when `remark` and `edit`

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
Update help window to include missing commands:
- help
- list
- schedule edit
- schedule delete
- clear
- remark
Changed `INDEX` to `SCHEDULE_INDEX` for schedule edit and delete
Edit: Added schedule clear
Edit2: Changed `clear` from `Clears Candidate and Interview lists` to `Clears all data in the system`, enlarged command box to be inline with the last sub-command.
Closes #279
> Update help window

- docs/UserGuide.md
- Added additional section to address the scope of `course` entity
- Updated introduction/target user profile with further constraints to `NUS School of Computing professors`
Closes #324.
> Issue #324: Add restriction on `course` entity in UG

- src/main/java/seedu/address/ui/MainWindow.java
@charmainehly this one is my implementation !! I added a `return commandResult` from the `edit command` to short circuit the `executeCommand` so that it won't run twice!!
> Issue #344: Bug from `edit` after using `find` command

- docs/UserGuide.md
This PR consits of the following changes:
- Addressed `seniority` in notes section under `Features` header (info `div`)
- Added format of `studentId` for clarity
- Ensured periods are added at the end of points in `add` and `edit` commands
- Improved bullet points of `add` command
- Updated `edit` command format to show that at least 1 field must be present when the `edit INDEX` command is run, for clarity
Closes these issues:
Closes #331.
Closes #338.
Closes #339.
Closes #345.
> Issues #331, #338, #339, #345: Update UG for `add` and `edit`

- src/main/java/seedu/address/ui/MainWindow.java
Bugs reported:
#343 
1. `focus 2`
2. `schedule add candidate/2 at/04-04-2022 11:00`
3. `schedule clear`
Error message was displayed incorrectly. This was due to the fact that the schedule was cleared first, no longer able to get the `Candidate` from the `InterviewList`
#315 
`schedule clear` when the user types `view today` with an empty list.
This is also related to #343, as the updated `InterviewList` is empty, unable to retrieve `Candidate` from the updated `InterviewList`. 
In this PR, I have ensured to get the index of the `Candidate` before deleting them. It works on my end now!
Closes #343 
Closes #315
> Schedule Feedback Bug

- src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
- src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
- src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
- src/main/java/seedu/address/model/InterviewSchedule.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/interview/UniqueInterviewList.java
- src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
- src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
- src/test/java/seedu/address/model/InterviewScheduleTest.java
- src/test/java/seedu/address/model/interview/UniqueInterviewListTest.java
- src/test/java/seedu/address/testutil/TypicalInterviews.java
@tiewweijian @domlimm @charmainehly @LeeEnEn Do help to test the edit schedule command to see if nothing breaks as a result of my changes! I tested quite extensively and it works but we never know 😆 
Summary of changes: 
- Abstracted the main logic away from the `execute` function of `EditScheduleCommand` to the lower-level in `UniqueInterviewList`. 
- Followed AB3's logic to first execute the changes on a copy of the `internalList` to check for conflicts before calling the `set` method.
- Another reason for the change was also because the `setInterview` method became redundant, but it is present in the chain of `ModelManager`, `InterviewSchedule`, `UniqueInterviewList` and test cases.
- Added more test cases to test for rescheduling of the same candidate.
- Improve code quality for …
> Improve code quality and add test cases

- docs/DeveloperGuide.md
Under the segment `Instructions for Manual Testing` 
closes #398 
closes #413
> Update Focus and Startup in Developers Guide 
